### ISSUE TITLE
deploy.sh fails to compile with gcc 15.2.0 on Ubuntu.

### ISSUE THREAD

**Issue by RorschachRev** [LuminariMUD/Luminari-Source#44]
**Describe the bug**
Failure to compile, based on script. Was able to compile previously with the same version, but unable to reproduce successful compile. Several compiler libraries were replaced by running script, unknown what the original libraries were.

**To Reproduce**
./scripts/deploy.sh --auto --dev --init-world
Fails with: 
gcc -DHAVE_CONFIG_H -I. -I../src    -I../src -g -O2 -MT wld2html.o -MD -MP -MF $depbase.Tpo -c -o wld2html.o wld2html.c &&\
mv -f $depbase.Tpo $depbase.Po
rebuildMailIndex.c:31:3: error: expected ‘;’, identifier or ‘(’ before ‘bool’
   31 | } bool;
      |   ^~~~
rebuildMailIndex.c:31:3: warning: useless type name in empty declaration
make[2]: *** [Makefile:468: rebuildMailIndex.o] Error 1
wld2html.c:64:14: error: ‘bool’ cannot be defined via ‘typedef’
   64 | typedef char bool;

**Expected behavior**
Compile.

**Desktop (please complete the following information):**
 OS: Ubuntu Questing
gcc version 15.2.0 (Ubuntu 15.2.0-4ubuntu4) 

**Additional context**
Reading about the error, this was declared "not standard behavior." Attempting to add library to util/wld2html.c did not help.
#include <stdbool.h>
I would personally *never* expect a C bool to be a single character.
